# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_voted1'),
    ]

    operations = [
        migrations.AddField(
            model_name='texta',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
