# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_texta_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='suba',
            name='newpar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='texta',
            name='newpar',
            field=models.BooleanField(default=False),
        ),
    ]
