# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_story1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suba',
            old_name='newpar',
            new_name='paragraph',
        ),
        migrations.RenameField(
            model_name='texta',
            old_name='newpar',
            new_name='paragraph',
        ),
    ]
