# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20170404_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story1',
            old_name='para',
            new_name='text',
        ),
    ]
