# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 04:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0009_story2_story3_story4_subb_subc_subd_textb_textc_textd_voted2_voted3_voted4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('prompt', models.CharField(max_length=1000)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('muse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Story_by_paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Story')),
            ],
        ),
        migrations.CreateModel(
            name='Story_by_submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('vote', models.IntegerField(default=0)),
                ('paragraph', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Story')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('vote', models.IntegerField()),
                ('paragraph', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Story')),
            ],
        ),
        migrations.CreateModel(
            name='Voted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted', models.BooleanField(default=False)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Story')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Story1',
        ),
        migrations.DeleteModel(
            name='Story2',
        ),
        migrations.DeleteModel(
            name='Story3',
        ),
        migrations.DeleteModel(
            name='Story4',
        ),
        migrations.RemoveField(
            model_name='suba',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subb',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subc',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subd',
            name='author',
        ),
        migrations.RemoveField(
            model_name='texta',
            name='author',
        ),
        migrations.RemoveField(
            model_name='textb',
            name='author',
        ),
        migrations.RemoveField(
            model_name='textc',
            name='author',
        ),
        migrations.RemoveField(
            model_name='textd',
            name='author',
        ),
        migrations.RemoveField(
            model_name='voted1',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='voted2',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='voted3',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='voted4',
            name='voter',
        ),
        migrations.DeleteModel(
            name='Suba',
        ),
        migrations.DeleteModel(
            name='Subb',
        ),
        migrations.DeleteModel(
            name='Subc',
        ),
        migrations.DeleteModel(
            name='Subd',
        ),
        migrations.DeleteModel(
            name='Texta',
        ),
        migrations.DeleteModel(
            name='Textb',
        ),
        migrations.DeleteModel(
            name='Textc',
        ),
        migrations.DeleteModel(
            name='Textd',
        ),
        migrations.DeleteModel(
            name='Voted1',
        ),
        migrations.DeleteModel(
            name='Voted2',
        ),
        migrations.DeleteModel(
            name='Voted3',
        ),
        migrations.DeleteModel(
            name='Voted4',
        ),
    ]
