# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 19:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0011_story_popularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voted',
            name='story',
        ),
        migrations.RemoveField(
            model_name='voted',
            name='voter',
        ),
        migrations.AddField(
            model_name='story',
            name='voted',
            field=models.ManyToManyField(related_name='voted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='muse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Voted',
        ),
    ]
