# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 17:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20170513_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='vote_frequency',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)]),
            preserve_default=False,
        ),
    ]
