# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 03:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_story_vote_frequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='vote_minimum',
            new_name='minimum_votes',
        ),
        migrations.RemoveField(
            model_name='story',
            name='vote_frequency',
        ),
        migrations.AddField(
            model_name='story',
            name='minutes_between_votes',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(60)]),
            preserve_default=False,
        ),
    ]
