# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20170516_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='calcvote_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
